[package]
name = "aittributor"
version = "0.4.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
sysinfo = "0.32"
whoami = "2.1.0"

[dev-dependencies]
tempfile = "3.24.0"
